server:
  port: 8001

spring:
  application:
    name: payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root123456


mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.mycloud.api.entities


eureka:
  client:
    register-with-eureka: true #是否将自己注册进 eureka服务端，默认为 true
    service-url:
      defaultZone: http://localhost:7001/eureka
    fetch-registry: true #是否从 eureka server 抓取已有的注册信息，默认为 true.单节点无所谓，集群必须设置为 true才能配合 ribbon 使用负载均衡